package projeto.a3;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class TelaModificarRequisitos extends javax.swing.JFrame {

    /**
     * Creates new form TelaModificarRequisitos
     */
    public TelaModificarRequisitos() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTableRequi.getModel();
        jTableRequi.setRowSorter(new TableRowSorter(modelo));
        readJTable();
        this.setResizable(false);
        

    }
    
    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTableRequi.getModel();
        modelo.setNumRows(0);
        RequisitosDao requiDao = new RequisitosDao();

        for (Requisitos requi : requiDao.read()) {

            modelo.addRow(new Object[]{
                requi.getId(),
                requi.getProjeto(),
                requi.getNome(),
                requi.getModulo(),
                requi.getFuncoes(),
                requi.getDataCriacao(),
                requi.getAutor(),
                requi.getAutorUltAlt(),
                requi.getDataUltMod(),
                requi.getVersao(),
                requi.getPrior(),
                requi.getComplex(),
                requi.getEsfHoras(),
                requi.getEstado(),
                requi.getFase(),
                requi.getDescricao()
                
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        projetoString = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        atualizarBotao = new javax.swing.JButton();
        removerBotao = new javax.swing.JButton();
        cadastrarBotao = new javax.swing.JButton();
        nomeString = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        moduloString = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dataString = new javax.swing.JTextField();
        dataCriacao = new javax.swing.JLabel();
        autorString = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        autUltAlt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        versaoString = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        priorString = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        esfHorasString = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        estadoString = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        faseString = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        complexString = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        funcString = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        descString = new javax.swing.JTextArea();
        dataUltMod = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableRequi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar requisitos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.blue);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        projetoString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projetoStringActionPerformed(evt);
            }
        });

        jLabel1.setText("Projeto:");

        atualizarBotao.setBackground(new java.awt.Color(255, 255, 255));
        atualizarBotao.setText("Atualizar");
        atualizarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBotaoActionPerformed(evt);
            }
        });

        removerBotao.setBackground(new java.awt.Color(255, 255, 255));
        removerBotao.setText("Remover");
        removerBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBotaoActionPerformed(evt);
            }
        });

        cadastrarBotao.setBackground(new java.awt.Color(255, 255, 255));
        cadastrarBotao.setText("Cadastrar");
        cadastrarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBotaoActionPerformed(evt);
            }
        });

        nomeString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeStringActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        moduloString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloStringActionPerformed(evt);
            }
        });

        jLabel3.setText("Módulo:");

        jLabel4.setText("Funções:");

        dataString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataStringActionPerformed(evt);
            }
        });

        dataCriacao.setText("Data de criação: ");

        autorString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorStringActionPerformed(evt);
            }
        });

        jLabel6.setText("Autor:");

        autUltAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autUltAltActionPerformed(evt);
            }
        });

        jLabel7.setText("Autor da última alteração:");

        jLabel8.setText("Data da última modificação:");

        versaoString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versaoStringActionPerformed(evt);
            }
        });

        jLabel9.setText("Versão:");

        priorString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorStringActionPerformed(evt);
            }
        });

        jLabel10.setText("Prioridade:");

        esfHorasString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esfHorasStringActionPerformed(evt);
            }
        });

        jLabel12.setText("Esforço em horas:");

        estadoString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoStringActionPerformed(evt);
            }
        });

        jLabel13.setText("Estado:");

        faseString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faseStringActionPerformed(evt);
            }
        });

        jLabel14.setText("Fase:");

        jLabel15.setText("Descrição:");

        complexString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complexStringActionPerformed(evt);
            }
        });

        jLabel16.setText("Complexidade:");

        funcString.setColumns(20);
        funcString.setRows(5);
        jScrollPane1.setViewportView(funcString);

        descString.setColumns(20);
        descString.setRows(5);
        jScrollPane2.setViewportView(descString);

        jTableRequi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Projeto", "Nome", "Módulo", "Funções", "Data de criação", "Autor", "Autor da última alteração", "Data da última modificação", "Versão", "Prioridade", "Complexidade", "Esforço em horas", "Estado", "Fase", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRequi.setGridColor(new java.awt.Color(255, 255, 255));
        jTableRequi.getTableHeader().setReorderingAllowed(false);
        jTableRequi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRequiMouseClicked(evt);
            }
        });
        jTableRequi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableRequiKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTableRequi);
        if (jTableRequi.getColumnModel().getColumnCount() > 0) {
            jTableRequi.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(atualizarBotao)
                        .addGap(29, 29, 29)
                        .addComponent(removerBotao)
                        .addGap(29, 29, 29)
                        .addComponent(cadastrarBotao))
                    .addComponent(estadoString, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(esfHorasString, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(complexString, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(faseString, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moduloString, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(nomeString, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(projetoString, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addComponent(priorString, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(versaoString, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dataUltMod, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(autUltAlt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(dataString, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataCriacao)
                    .addComponent(autorString, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1337, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projetoString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moduloString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dataCriacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autorString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autUltAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataUltMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versaoString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priorString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(complexString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(esfHorasString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estadoString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(faseString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removerBotao)
                    .addComponent(atualizarBotao)
                    .addComponent(cadastrarBotao))
                .addGap(33, 33, 33))
            .addComponent(jScrollPane4)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projetoStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projetoStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projetoStringActionPerformed

    private void atualizarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBotaoActionPerformed
        // TODO add your handling code here:

        if (jTableRequi.getSelectedRow() != -1) {
            Requisitos requi = new Requisitos();
            RequisitosDao requiDao = new RequisitosDao();
            requi.setProjeto(projetoString.getText());
            requi.setNome(nomeString.getText());
            requi.setModulo(moduloString.getText());
            requi.setFuncoes(funcString.getText());
            requi.setDataCriacao(dataString.getText());
            requi.setAutor(autorString.getText());
            requi.setAutorUltAlt(autUltAlt.getText());
            requi.setDataUltMod(dataUltMod.getText());
            requi.setVersao(versaoString.getText());
            requi.setPrior(priorString.getText());
            requi.setComplex(complexString.getText());
            requi.setEsfHoras(esfHorasString.getText());
            requi.setEstado(estadoString.getText());
            requi.setFase(faseString.getText());
            requi.setDescricao(descString.getText());
            requi.setId((int) jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 0));
            requiDao.atualizar(requi);
            
            projetoString.setText("");
            nomeString.setText("");
            moduloString.setText("");
            funcString.setText("");
            dataString.setText("");
            autorString.setText("");
            autUltAlt.setText("");
            dataUltMod.setText(" ");
            versaoString.setText("");
            priorString.setText("");
            complexString.setText("");
            esfHorasString.setText("");
            estadoString.setText("");
            faseString.setText("");
            descString.setText("");
            

            readJTable();

            //            Usuario user = new Usuario();
            //            UsuarioMet uMet = new UsuarioMet();
            //
            //            user.setNome(nomeString.getText());
            //            user.setNomeUser(loginString.getText());
            //            user.setEmail(emailString.getText());
            //            user.setSenha(senhaString.getText());
            //            user.setTelefone(telefoneString.getText());
            //            user.setNomeUser(jTableUsers.getValueAt(jTableUsers.getSelectedRow(), 1).toString());
            //            uMet.atualizar(user);
            //
            //
            //            nomeString.setText("");
            //            loginString.setText("");
            //            emailString.setText("");
            //            senhaString.setText("");
            //            telefoneString.setText("");
            //
            //            readJTable();
            //

        }
    }//GEN-LAST:event_atualizarBotaoActionPerformed

    private void removerBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBotaoActionPerformed
        // TODO add your handling code here:
        if (jTableRequi.getSelectedRow() != -1) {
            Requisitos requi = new Requisitos();
            RequisitosDao requiDao = new RequisitosDao();

            requi.setId((int) jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 0));
            requiDao.deletar(requi);

            projetoString.setText("");
            nomeString.setText("");
            moduloString.setText("");
            funcString.setText("");
            dataString.setText("");
            autorString.setText("");
            autUltAlt.setText("");
            dataUltMod.setText(" ");
            versaoString.setText("");
            priorString.setText("");
            complexString.setText("");
            esfHorasString.setText("");
            estadoString.setText("");
            faseString.setText("");
            descString.setText("");

            readJTable();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um projeto para exclusão");
        }
    }//GEN-LAST:event_removerBotaoActionPerformed

    private void cadastrarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBotaoActionPerformed
        // TODO add your handling code here:
        Requisitos requi = new Requisitos();
        RequisitosDao requiDao = new RequisitosDao();
        requi.setProjeto(projetoString.getText());
        requi.setNome(nomeString.getText());
        requi.setModulo(moduloString.getText());
        requi.setFuncoes(funcString.getText());
        requi.setDataCriacao(dataString.getText());
        requi.setAutor(autorString.getText());
        requi.setAutorUltAlt(autUltAlt.getText());
        requi.setDataUltMod(projetoString.getText());
        requi.setVersao(versaoString.getText());
        requi.setPrior(priorString.getText());
        requi.setComplex(complexString.getText());
        requi.setEsfHoras(esfHorasString.getText());
        requi.setEstado(estadoString.getText());
        requi.setFase(faseString.getText());
        requi.setDescricao(descString.getText());
        requiDao.inserir(requi);

        projetoString.setText("");
        nomeString.setText("");
        moduloString.setText("");
        funcString.setText("");
        dataString.setText("");
        autorString.setText("");
        autUltAlt.setText("");
        dataUltMod.setText(" ");
        versaoString.setText("");
        priorString.setText("");
        complexString.setText("");
        esfHorasString.setText("");
        estadoString.setText("");
        faseString.setText("");
        descString.setText("");
        
        readJTable();

        //        DefaultTableModel jTableUser = (DefaultTableModel) jTableUsers.getModel();
        //        Object[] dados = {nomeString.getText(), loginString.getText(), emailString.getText(), senhaString.getText(), telefoneString.getText()};
        //        jTableUser.addRow(dados);
    }//GEN-LAST:event_cadastrarBotaoActionPerformed

    private void jTableRequiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRequiMouseClicked
        // TODO add your handling code here:
        if (jTableRequi.getSelectedRow() != -1) {
            projetoString.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 1).toString());
            nomeString.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 2).toString());
            moduloString.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 3).toString());
            funcString.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 4).toString());
            dataString.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 5).toString());
            autorString.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 6).toString());
            autUltAlt.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 7).toString());
            dataUltMod.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 8).toString());
            versaoString.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 9).toString());
            priorString.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 10).toString());
            complexString.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 11).toString());
            esfHorasString.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 12).toString());
            estadoString.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 13).toString());
            faseString.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 14).toString());
            descString.setText(jTableRequi.getValueAt(jTableRequi.getSelectedRow(), 15).toString());

        }
    }//GEN-LAST:event_jTableRequiMouseClicked

    private void jTableRequiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableRequiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableRequiKeyReleased

    private void nomeStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeStringActionPerformed

    private void moduloStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moduloStringActionPerformed

    private void dataStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataStringActionPerformed

    private void autorStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorStringActionPerformed

    private void autUltAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autUltAltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autUltAltActionPerformed

    private void versaoStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_versaoStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_versaoStringActionPerformed

    private void priorStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priorStringActionPerformed

    private void esfHorasStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esfHorasStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esfHorasStringActionPerformed

    private void estadoStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoStringActionPerformed

    private void faseStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faseStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faseStringActionPerformed

    private void complexStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complexStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complexStringActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaModificarRequisitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaModificarRequisitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaModificarRequisitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaModificarRequisitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaModificarRequisitos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarBotao;
    private javax.swing.JTextField autUltAlt;
    private javax.swing.JTextField autorString;
    private javax.swing.JButton cadastrarBotao;
    private javax.swing.JTextField complexString;
    private javax.swing.JLabel dataCriacao;
    private javax.swing.JTextField dataString;
    private javax.swing.JTextField dataUltMod;
    private javax.swing.JTextArea descString;
    private javax.swing.JTextField esfHorasString;
    private javax.swing.JTextField estadoString;
    private javax.swing.JTextField faseString;
    private javax.swing.JTextArea funcString;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableRequi;
    private javax.swing.JTextField moduloString;
    private javax.swing.JTextField nomeString;
    private javax.swing.JTextField priorString;
    private javax.swing.JTextField projetoString;
    private javax.swing.JButton removerBotao;
    private javax.swing.JTextField versaoString;
    // End of variables declaration//GEN-END:variables
}
