/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.a3;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author iagol
 */
public class TelaModificarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaModificarUsuario
     */
    public TelaModificarUsuario() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTableUsers.getModel();
        jTableUsers.setRowSorter(new TableRowSorter(modelo));
        readJTable();
        this.setResizable(false);

    }

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTableUsers.getModel();
        modelo.setNumRows(0);
        UsuarioDAO uMet = new UsuarioDAO();

        for (Usuario us : uMet.read()) {

            modelo.addRow(new Object[]{
                us.getId(),
                us.getNome(),
                us.getNomeUser(),
                us.getEmail(),
                us.getSenha(),
                us.getTelefone()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nomeString = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        loginString = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emailString = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        telefoneString = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        senhaString = new javax.swing.JPasswordField();
        atualizarBotao = new javax.swing.JButton();
        removerBotao = new javax.swing.JButton();
        cadastrarBotao = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de usuário");
        setBackground(new java.awt.Color(51, 0, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        nomeString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeStringActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        loginString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginStringActionPerformed(evt);
            }
        });

        jLabel2.setText("Login:");

        emailString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailStringActionPerformed(evt);
            }
        });

        jLabel3.setText("Email:");

        jLabel4.setText("Senha:");

        telefoneString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneStringActionPerformed(evt);
            }
        });

        jLabel5.setText("Telefone:");

        senhaString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaStringActionPerformed(evt);
            }
        });

        atualizarBotao.setBackground(new java.awt.Color(255, 255, 255));
        atualizarBotao.setText("Atualizar");
        atualizarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBotaoActionPerformed(evt);
            }
        });

        removerBotao.setBackground(new java.awt.Color(255, 255, 255));
        removerBotao.setText("Remover");
        removerBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBotaoActionPerformed(evt);
            }
        });

        cadastrarBotao.setBackground(new java.awt.Color(255, 255, 255));
        cadastrarBotao.setText("Cadastrar");
        cadastrarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(atualizarBotao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadastrarBotao)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(telefoneString)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(emailString)
                        .addComponent(jLabel3)
                        .addComponent(loginString)
                        .addComponent(jLabel2)
                        .addComponent(nomeString)
                        .addComponent(senhaString, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removerBotao)
                .addGap(135, 135, 135))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nomeString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(loginString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(emailString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(senhaString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(telefoneString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizarBotao)
                    .addComponent(cadastrarBotao))
                .addGap(18, 18, 18)
                .addComponent(removerBotao)
                .addGap(59, 59, 59))
        );

        jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome completo", "Login", "Email", "Senha", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsers.getTableHeader().setReorderingAllowed(false);
        jTableUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsersMouseClicked(evt);
            }
        });
        jTableUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableUsersKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTableUsers);
        if (jTableUsers.getColumnModel().getColumnCount() > 0) {
            jTableUsers.getColumnModel().getColumn(0).setResizable(false);
            jTableUsers.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableUsersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableUsersKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableUsersKeyReleased

    private void jTableUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsersMouseClicked
        // TODO add your handling code here:
        if (jTableUsers.getSelectedRow() != -1) {
            nomeString.setText(jTableUsers.getValueAt(jTableUsers.getSelectedRow(), 1).toString());
            loginString.setText(jTableUsers.getValueAt(jTableUsers.getSelectedRow(), 2).toString());
            emailString.setText(jTableUsers.getValueAt(jTableUsers.getSelectedRow(), 3).toString());
            senhaString.setText(jTableUsers.getValueAt(jTableUsers.getSelectedRow(), 4).toString());
            telefoneString.setText(jTableUsers.getValueAt(jTableUsers.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_jTableUsersMouseClicked

    private void cadastrarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBotaoActionPerformed
        // TODO add your handling code here:
        Usuario user = new Usuario();
        UsuarioDAO uMet = new UsuarioDAO();
        user.setNome(nomeString.getText());
        user.setNomeUser(loginString.getText());
        user.setEmail(emailString.getText());
        user.setSenha(senhaString.getText());
        user.setTelefone(telefoneString.getText());
        uMet.inserir(user);

        nomeString.setText("");
        loginString.setText("");
        emailString.setText("");
        senhaString.setText("");
        telefoneString.setText("");

        readJTable();

        //        DefaultTableModel jTableUser = (DefaultTableModel) jTableUsers.getModel();
        //        Object[] dados = {nomeString.getText(), loginString.getText(), emailString.getText(), senhaString.getText(), telefoneString.getText()};
        //        jTableUser.addRow(dados);
    }//GEN-LAST:event_cadastrarBotaoActionPerformed

    private void removerBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBotaoActionPerformed
        // TODO add your handling code here:
        if (jTableUsers.getSelectedRow() != -1) {
            Usuario user = new Usuario();
            UsuarioDAO uMet = new UsuarioDAO();

            user.setId((int) jTableUsers.getValueAt(jTableUsers.getSelectedRow(), 0));
            uMet.deletar(user);

            nomeString.setText("");
            loginString.setText("");
            emailString.setText("");
            senhaString.setText("");
            telefoneString.setText("");

            readJTable();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um usuário para exclusão");
        }
    }//GEN-LAST:event_removerBotaoActionPerformed

    private void atualizarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBotaoActionPerformed
        // TODO add your handling code here:

        if (jTableUsers.getSelectedRow() != -1) {
            Usuario user = new Usuario();
            UsuarioDAO uMet = new UsuarioDAO();
            user.setNome(nomeString.getText());
            user.setNomeUser(loginString.getText());
            user.setEmail(emailString.getText());
            user.setSenha(senhaString.getText());
            user.setTelefone(telefoneString.getText());
            user.setId((int) jTableUsers.getValueAt(jTableUsers.getSelectedRow(), 0));
            uMet.atualizar(user);

            nomeString.setText("");
            loginString.setText("");
            emailString.setText("");
            senhaString.setText("");
            telefoneString.setText("");

            readJTable();

            //            Usuario user = new Usuario();
            //            UsuarioMet uMet = new UsuarioMet();
            //
            //            user.setNome(nomeString.getText());
            //            user.setNomeUser(loginString.getText());
            //            user.setEmail(emailString.getText());
            //            user.setSenha(senhaString.getText());
            //            user.setTelefone(telefoneString.getText());
            //            user.setNomeUser(jTableUsers.getValueAt(jTableUsers.getSelectedRow(), 1).toString());
            //            uMet.atualizar(user);
            //
            //
            //            nomeString.setText("");
            //            loginString.setText("");
            //            emailString.setText("");
            //            senhaString.setText("");
            //            telefoneString.setText("");
            //
            //            readJTable();
            //

        }
    }//GEN-LAST:event_atualizarBotaoActionPerformed

    private void senhaStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaStringActionPerformed

    private void telefoneStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneStringActionPerformed

    private void emailStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailStringActionPerformed

    private void loginStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginStringActionPerformed

    private void nomeStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeStringActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaModificarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarBotao;
    private javax.swing.JButton cadastrarBotao;
    private javax.swing.JTextField emailString;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableUsers;
    private javax.swing.JTextField loginString;
    private javax.swing.JTextField nomeString;
    private javax.swing.JButton removerBotao;
    private javax.swing.JPasswordField senhaString;
    private javax.swing.JTextField telefoneString;
    // End of variables declaration//GEN-END:variables
}
